### ISSUE TITLE
Alert emails: sync app units to triggered alert email

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi-network-serverless#127] opened 2021-08-22 10:13 UTC
Description:

User changed temperature units from celsius to kelvin in app and synced to network. Next time his temperature alert triggered he received alert according to celsius range. Also his units are not mentioned in email.

Please use selected units in alerts and mention unit in alert email.

@laurijamsa approve?

**Comment by laurijamsa** [comment] 2021-08-22 16:48
Yes, this is definitely something we'll need to make better. But this is not an urgent issue and I'm moving this to the backlog for now.

**Comment by Muhwu** [comment] 2021-08-28 21:58
There's also something I didn't previously realize regarding conversions in general - it currently does not do an actual conversion, simply displays a unit. The temperatures, as far as I know, always come from Gateway in the same format so this is simply an e-mail conversion we need to make.

So there are two action points here:
1. Actually make a proper conversion, not just switch C to F.
2. Other supported units based on settings and their respective conversions

One thing of note though; even though user settings allows the use of any string values, it looks like for `UNIT_HUMIDITY` and `UNIT_PRESSURE`, some sort of magic constants are being used and I currently have no way of knowing what these refer to:
![image](https://user-images.githubusercontent.com/9969729/131232032-1620940a-34fe-430b-a6be-9198e459ff45.png)

@laurijamsa @markoaamunkajo

**Comment by laurijamsa** [comment] 2021-08-29 05:29
These other magic constants are used and unified on the android/ios/web apps already, but not documented I think. So, please @io53  @andreevdenis or @rinat-enikeev specify here what they mean.

**Comment by andreevdenis** [comment] 2021-09-02 18:39
Magic constants for humidity:
0 - Relative (%),
1 - Absolute (g/m³),
2 - Dew point (°)

Magic constants for pressure:
0 - Pascal (Pa),
1 - Hectopascal (hPa),
2 - Millimetre of mercury (mmHg),
3 - Inch of mercury (inHg)

**Comment by laurijamsa** [comment] 2021-09-04 06:45
I just quickly tested this and it works for me. Except, like I wrote here https://github.com/ruuvi/ruuvi-network-serverless/issues/127#issuecomment-906337109, currently, we don't support alerts for other than relative humidity.

The email I got "Holopaisen kasvihuone has reached 76.03 g/m³ (humidity) that is over the threshold of 24 g/m³" is not correct, because my alert settings was "alert if less than 0 or more then 24% relative humidity".

Let's remove the humidity conversions.

**Comment by Muhwu** [comment] 2021-09-04 17:34
Hey @laurijamsa , quick questio - were your app settings set to g/m³ ? I checked the settings and they should have been set to relative humidity.

Either way, I'm disabling the conversions for it - but it should have accurately given you the relative humidity unless the settings were different at the time (and I tried on my account and I do - indeed - receive correctly formatted ones).

**Comment by laurijamsa** [comment] 2021-09-04 18:01
Yes, my settings were set to absolute humidity so that I could spot issues 🙂 Even if user would use absolute humidity on the app, the email should not contain those units because only relative humidity alerts are supported.

**Comment by Muhwu** [comment] 2021-09-05 14:11
Got it. Thanks!

**Comment by Muhwu** [comment] 2021-09-06 15:56
Currently only % is used for humidity.

**Comment by laurijamsa** [comment] 2021-09-07 14:07
Confirmed to work. Thanks!

**Closed by laurijamsa** 2021-09-07 14:07 UTC
Labels: bug
